# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-22 21:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisFindings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('static_code_analysis', models.CharField(max_length=50000)),
                ('dynamic_code_analysis', models.CharField(max_length=50000)),
                ('others', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='MalwareCharacteristic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capabilities_for_infecting_files', models.CharField(max_length=10000)),
                ('self_preservation', models.CharField(max_length=10000)),
                ('leaking_data', models.CharField(max_length=10000)),
                ('interaction_with_attackers', models.CharField(max_length=10000)),
                ('others', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='MalwareDependencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_files', models.CharField(max_length=1000)),
                ('others', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='MalwareFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('malware_name', models.CharField(max_length=100)),
                ('found_date', models.DateTimeField(verbose_name='date found')),
                ('malwar_type', models.CharField(choices=[('ROOTKIT', 'Rootkit'), ('BACKDOOR', 'Backdoor'), ('VIRUS', 'Virus'), ('KEYLOGGER', 'Keylogger'), ('TROJAN', 'Trojan'), ('WORM', 'Worm'), ('ADWARE', 'Adware'), ('SPYWERE', 'Spywere'), ('DIALER', 'Dialer'), ('OTROS', 'Otros'), ('OTHER', 'Other')], default='VIRUS', max_length=50)),
                ('antyvirus_detection_capabilities', models.CharField(max_length=3000)),
                ('file_type', models.CharField(choices=[('EXE', 'Exe'), ('OTHER', 'Other')], default='EXE', max_length=10)),
                ('analysis_findings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporter.AnalysisFindings')),
                ('malware_cependencies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporter.MalwareDependencies')),
                ('malware_characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporter.MalwareCharacteristic')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(verbose_name='date of creation')),
                ('report_name', models.CharField(max_length=100)),
                ('additional_findings', models.CharField(max_length=10000)),
                ('additional_recommendations', models.CharField(max_length=10000)),
                ('report_type', models.CharField(choices=[('FULL REPORT', 'Full report'), ('NOT FULL REPORT', 'Not full report')], default='FULL REPORT', max_length=100)),
                ('malware_file_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporter.MalwareFile')),
            ],
        ),
        migrations.CreateModel(
            name='SupportingFigures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logs', models.CharField(max_length=10000)),
                ('other', models.CharField(max_length=10000)),
            ],
        ),
        migrations.AddField(
            model_name='malwarefile',
            name='supporting_figures',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporter.SupportingFigures'),
        ),
    ]
