# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-23 21:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0002_auto_20161022_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='malwarefile',
            name='found_place',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='malwarefile',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
