# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-25 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0003_auto_20161023_2301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supportingfigures',
            old_name='other',
            new_name='others',
        ),
        migrations.AddField(
            model_name='malwaredependencies',
            name='custom_DLLs',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='malwaredependencies',
            name='executables',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='malwaredependencies',
            name='scripts',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='malwaredependencies',
            name='support_OS_version',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='malwaredependencies',
            name='urls',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
