# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-25 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0004_auto_20161025_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisfindings',
            name='dynamic_code_analysis',
            field=models.TextField(max_length=50000),
        ),
        migrations.AlterField(
            model_name='analysisfindings',
            name='others',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='analysisfindings',
            name='static_code_analysis',
            field=models.TextField(max_length=50000),
        ),
        migrations.AlterField(
            model_name='malwarecharacteristic',
            name='capabilities_for_infecting_files',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='malwarecharacteristic',
            name='interaction_with_attackers',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='malwarecharacteristic',
            name='leaking_data',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='malwarecharacteristic',
            name='others',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='malwarecharacteristic',
            name='self_preservation',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='malwaredependencies',
            name='custom_DLLs',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='malwaredependencies',
            name='executables',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='malwaredependencies',
            name='others',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='malwaredependencies',
            name='required_files',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='malwaredependencies',
            name='scripts',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='malwaredependencies',
            name='urls',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='malwarefile',
            name='antyvirus_detection_capabilities',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='report',
            name='additional_findings',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='report',
            name='additional_recommendations',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='supportingfigures',
            name='logs',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='supportingfigures',
            name='others',
            field=models.TextField(max_length=10000),
        ),
    ]
