# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-25 19:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0005_auto_20161025_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='malwarefile',
            old_name='malwar_type',
            new_name='malware_type',
        ),
    ]
