# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-25 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0006_auto_20161025_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malwaredependencies',
            name='support_OS_version',
            field=models.CharField(choices=[('WINDOWS', 'Windows'), ('LINUX', 'Linux'), ('UNIX', 'UNIX'), ('OS', 'OS')], default='WINDOWS', max_length=50),
        ),
    ]
