# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-26 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0007_auto_20161025_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportingfigures',
            name='logs',
            field=models.TextField(default='dada'),
        ),
        migrations.AlterField(
            model_name='supportingfigures',
            name='others',
            field=models.TextField(default='da'),
        ),
    ]
