# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-26 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0008_auto_20161026_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportingfigures',
            name='logs',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='supportingfigures',
            name='others',
            field=models.TextField(max_length=10000),
        ),
    ]
