# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-26 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0009_auto_20161026_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisfindings',
            name='dynamic_code_analysis',
            field=models.TextField(blank=True, max_length=50000),
        ),
        migrations.AlterField(
            model_name='analysisfindings',
            name='others',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='analysisfindings',
            name='static_code_analysis',
            field=models.TextField(blank=True, max_length=50000),
        ),
        migrations.AlterField(
            model_name='malwarecharacteristic',
            name='capabilities_for_infecting_files',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='malwarecharacteristic',
            name='interaction_with_attackers',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='malwarecharacteristic',
            name='leaking_data',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='malwarecharacteristic',
            name='others',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='malwarecharacteristic',
            name='self_preservation',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='malwaredependencies',
            name='custom_DLLs',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='malwaredependencies',
            name='executables',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='malwaredependencies',
            name='others',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='malwaredependencies',
            name='required_files',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='malwaredependencies',
            name='scripts',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='malwaredependencies',
            name='support_OS_version',
            field=models.CharField(blank=True, choices=[('WINDOWS', 'Windows'), ('LINUX', 'Linux'), ('UNIX', 'UNIX'), ('OS', 'OS')], default='WINDOWS', max_length=50),
        ),
        migrations.AlterField(
            model_name='malwaredependencies',
            name='urls',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='malwarefile',
            name='antyvirus_detection_capabilities',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='malwarefile',
            name='file_type',
            field=models.CharField(blank=True, choices=[('EXE', 'Exe'), ('OTHER', 'Other')], default='EXE', max_length=10),
        ),
        migrations.AlterField(
            model_name='malwarefile',
            name='found_date',
            field=models.DateTimeField(blank=True, verbose_name='date found'),
        ),
        migrations.AlterField(
            model_name='malwarefile',
            name='found_place',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='malwarefile',
            name='malware_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='malwarefile',
            name='malware_type',
            field=models.CharField(blank=True, choices=[('ROOTKIT', 'Rootkit'), ('BACKDOOR', 'Backdoor'), ('VIRUS', 'Virus'), ('KEYLOGGER', 'Keylogger'), ('TROJAN', 'Trojan'), ('WORM', 'Worm'), ('ADWARE', 'Adware'), ('SPYWERE', 'Spywere'), ('DIALER', 'Dialer'), ('OTROS', 'Otros'), ('OTHER', 'Other')], default='VIRUS', max_length=50),
        ),
        migrations.AlterField(
            model_name='malwarefile',
            name='size',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='report',
            name='additional_findings',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='report',
            name='additional_recommendations',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='report',
            name='create_date',
            field=models.DateTimeField(blank=True, verbose_name='date of creation'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(blank=True, choices=[('FULL REPORT', 'Full report'), ('NOT FULL REPORT', 'Not full report')], default='FULL REPORT', max_length=100),
        ),
        migrations.AlterField(
            model_name='supportingfigures',
            name='logs',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='supportingfigures',
            name='others',
            field=models.TextField(blank=True, max_length=10000),
        ),
    ]
