# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-27 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0010_auto_20161027_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='create_date',
            field=models.DateField(blank=True, verbose_name='date of creation'),
        ),
    ]
