# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-27 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0011_auto_20161027_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malwarefile',
            name='found_date',
            field=models.DateField(blank=True, verbose_name='date found'),
        ),
        migrations.AlterField(
            model_name='report',
            name='create_date',
            field=models.DateField(blank=True, default='2016-05-09', verbose_name='date of creation'),
        ),
    ]
